### ISSUE TITLE
Is there a way control the interval between the animations?

### ISSUE THREAD

**Issue by nglauber** [valentinilk/compose-shimmer#1]
Hi. First of all, congratulations for the library. It's very useful. 
Could you tell me if there's a way to control the interval between the animation? 
And/Or set the animation's duration?

I'm using in my app and (fortunately) the backend respond very quickly so very often it's not possible to see the animation even once...

Thanks in advance.

**Comment by valentinilk** [comment]
Hi @nglauber, thanks for using the library.

The animation can be altered by overriding the default theme. A good example can be found here: [LoadingCardSample.kt](https://github.com/valentinilk/compose-shimmer/blob/359a0e9d74276fa18f2b545e3bfd9ade5b260477/app/src/main/java/com/valentinilk/shimmer/sample/theming/LoadingCardSample.kt)

In your case overriding the `animationSpec` is probably sufficient. So maybe add the following right after you set the `MaterialTheme` in your application. Hope that helps. :)

```
private val shimmerTheme = defaultShimmerTheme.copy(
    animationSpec = infiniteRepeatable(
        animation = tween(
            durationMillis = 600,
            delayMillis = 200,
            easing = LinearEasing,
        ),
        repeatMode = RepeatMode.Restart,
    ),
)

@Composable
fun Sample() {
    MaterialTheme {
        CompositionLocalProvider(
            LocalShimmerTheme provides shimmerTheme
        ) {
            // Your content
        }
    }
}
```

**Comment by nglauber** [comment]
Awesome! Worked like a charm ;) 
Thanks and congratulations again!
