### ISSUE TITLE
Use `Modifier.Node` API instead of `composed`

### ISSUE THREAD

**Issue by lwasyl** [valentinilk/compose-shimmer#30]
According to the documentation, `Modifier.composed` is discouraged due to performance concerns. The recommended API is now `Modifier.Node` and friends: https://developer.android.com/develop/ui/compose/custom-modifiers#implement-custom, or alternatively (but not without downsides) a `@Composable Modifier.modifierFactory(): Modifier` factory function.

Have you looked into whether it's possible to migrate to either of the two approaches?

**Comment by valentinilk** [comment]
This change is finally included in [1.3.1](https://github.com/valentinilk/compose-shimmer/releases/tag/v1.3.1). Unfortunately I still had to use a `@Composable` factory, but at least the `composed` modifier is gone. I tried to get rid of the factory as well, but it would have required too many changes.

PR:
https://github.com/valentinilk/compose-shimmer/pull/36
